    version: '3.9'
    services:
      es03:
        image: elasticsearch:7.6.2
        container_name: es03
        environment:
          -  "ES_JAVA_OPTS=-Xms6g -Xmx6g"
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
        volumes:
          - /root/elk/es03/data:/usr/share/elasticsearch/data
          - /root/elk/es03/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
          - 9200:9200
          - 9300:9300
        networks:
          - elk
    networks:
      elk:
        driver: bridge