version: '3.9'
services:
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    volumes:
      - /root/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elk
networks:
  elk:
    driver: bridge