version: '3'
services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: mssqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql:/var/opt/mssql